sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
  - pip install -U molecule docker-py testinfra ansible ansible-lint
script:
  - molecule test
