---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Ensure the ZNC admin group is present
  group: name="{{ znc_exec_user }}" gid="{{ znc_exec_user_and_group_id }}"

- name: Ensure the ZNC admin user is present
  user: name="{{ znc_exec_user }}" group="{{ znc_exec_user }}" uid="{{ znc_exec_user_and_group_id }}"

- name: Ensure the ZNC configuration directory is present
  file: state=directory path={{ znc_config_root }}/configs group="{{ znc_exec_user }}" owner="{{ znc_exec_user }}"

- name: Ensure the ZNC configuration file is present
  template: src=znc.conf.j2 dest={{ znc_config_root }}/configs/znc.conf group="{{ znc_exec_user }}" owner="{{ znc_exec_user }}"
  no_log: True
  notify: restart znc
