---
- name: Ensure dependencies are present
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - libssl-dev
    - libperl-dev
    - pkg-config

- name: find the version of znc currently installed, if any
  shell: '/usr/local/bin/znc --version | grep -Poh "^ZNC \K([0-9.]+)"'
  ignore_errors: yes
  register: znc_installed_version

- name: install ZNC from source
  include: install_from_source.yml
  when: (znc_installed_version.rc != 0) or (znc_install_version | version_compare(znc_installed_version.stdout, "!="))

- name: Ensure the ZNC admin user is present
  user: name="{{ znc_exec_user }}"

- name: Ensure the ZNC upstart file is installed
  template: src=znc.conf.upstart.j2 dest=/etc/init/znc.conf
  notify: restart znc

- name: Ensure the ZNC configuration directory is present
  file: path={{ znc_datadir }}/configs state=directory owner={{ znc_exec_user }} group={{ znc_exec_user }}

- name: Ensure the ZNC configuration file is present
  template: src=znc.conf.j2 dest={{ znc_datadir }}/configs/znc.conf owner={{ znc_exec_user }} group={{ znc_exec_user }}
  notify: restart znc

- name: Ensure a Self-signed SSL certificate exists for ZNC
  command: "/usr/local/bin/znc --datadir={{ znc_datadir }} --makepem"
  args:
    creates: "{{ znc_datadir }}/znc.pem"
  sudo: yes
  sudo_user: "{{ znc_exec_user }}"
  notify: restart znc

- name: Ensure the ZNC service is started
  service: name=znc state=started
