---
- name: restart znc
  docker_container:
    name: znc
    image: "znc:{{ znc_docker_image_version }}"
    state: started
    restart: true
    restart_policy: always
    published_ports:
      - "{{ znc_port }}:{{ znc_port }}"
    volumes:
      - "/znc-data:/znc-data/"
